import type {Metadata} from "next";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";
import "./globals.css";
import "../style/theme.css";
import {AuthProvider} from "@/Providers";


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body className={` bg-gray-200 font-sans text-gray-950 dark:text-white antialiased [overflow-anchor:none]`}>
        <div className="bg-pebble text-eggplant">
            <AuthProvider>
                <Navbar/>
                <main className="flex-auto">

                    {children}

                </main>
                <Footer/>
            </AuthProvider>
        </div>
        </body>
        </html>
    );
}
